name: dfnightselfies
description: An application to take selfies in low light conditions

version: 2.0.0+40

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  album_saver:
  camera:
  esys_flutter_share:
  flutter_material_color_picker:
  intl:
  path_provider:
  path:
  permission_handler:
  screen:
  video_player:

  cupertino_icons: ^0.1.2
  native_device_orientation:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true