name: dfnightselfies
description: An application to take selfies in low light conditions

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera:
  flutter_material_color_picker:
  path_provider:
  path:
  screen:

  cupertino_icons: ^0.1.2
  native_device_orientation:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true