name: dfnightselfies
description: An application to take selfies in low light conditions

version: 2.3.0+57

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera:
  cupertino_icons:
  device_display_brightness:
  flutter_colorpicker:
  gallery_saver:
  intl:
  native_device_orientation:
  path:
  permission_handler:
  share_plus:
  shared_preferences:
  video_player:

dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path_android: "images/launcher_rounded.png"
  image_path_ios: "images/launcher.png"