name: dfnightselfies
description: An application to take selfies in low light conditions

version: 2.0.0+42

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  album_saver:
  camera:
    git:
      url: git://github.com/tengio/plugins.git
      ref: 310a8f06c4981121a5553b0f6f3a8cdf475b8af1
      path: packages/camera
  cupertino_icons: ^0.1.2
  esys_flutter_share:
  flutter_launcher_icons:
  flutter_material_color_picker:
  intl:
  native_device_orientation:
  path_provider:
  path:
  permission_handler:
  screen:
  video_player:
    git:
      url: git://github.com/tengio/plugins.git
      ref: 310a8f06c4981121a5553b0f6f3a8cdf475b8af1
      path: packages/video_player

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


flutter_icons:
  android: true
  ios: true
  image_path: "images/launcher.png"