name: dfnightselfies
description: An application to take selfies in low light conditions

version: 2.0.0+48

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera:
  cupertino_icons:
  esys_flutter_share:
  flutter_material_color_picker:
  gallery_saver:
  intl:
  native_device_orientation:
  path:
  path_provider:
  permission_handler:
  screen:
  shared_preferences:
  video_player:

dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


flutter_icons:
  android: true
  ios: true
  image_path_android: "images/launcher.png"
  image_path_ios: "images/launcher_full.png"